{% set name = "async" %}
{% set version = "2.5.0" %}
{% set sha256 = "0c49a62ece830a0a0c00dcaab8f49c3c762cea5f417add33552276e7bc6705ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/caolan/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g async
  requires:
    - nodejs
   

about:
  home: https://github.com/caolan/async
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Async utilities for node and the browser'
  description: |
    Async is a utility module which provides straight-forward, powerful functions for working with asynchronous JavaScript. 
  doc_url: https://caolan.github.io/async/
  dev_url: https://github.com/caolan/async

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
