{% set name = "async" %}
{% set version = "2.4.1" %}
{% set sha256 = "59e87c8cae51ae2a91782a7dffde5d1710ba281a67c2da8ea380ba2cdd5730eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/caolan/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g async
  requires:
    - nodejs
   

about:
  home: https://github.com/caolan/async
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Async utilities for node and the browser'
  description: |
    Async is a utility module which provides straight-forward, powerful functions for working with asynchronous JavaScript. 
  doc_url: https://caolan.github.io/async/
  dev_url: https://github.com/caolan/async

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
