travis:
  secure:
    BINSTAR_TOKEN: YjWephPZXabqfo6n/pm4vgYPVSmiztV3+/HIHtoL5p1LzAHagihVpvFI8eyFNKlPuJK8v8qeqRBP1eY//JiHZ4IeF1VjXcgLeQoAHo9k0JIVrHP7qajH+hyepFrz22bX76t3478OI/0k31p4uwa/sX+ZVSFhVbKAs1BOKmCwNRDWKmhQukUT904oKV/I44oAhul1X6leCOnhJsZ4RwrVio1m5v6GnvKZYJUMtPZbEXS21fiOxfFbcv4a6M4DVHsrx2xijwgvoxfz9l3PiK8CxMLwREkvPF933EKrLtlO78XglnvtV86cf8e9SqEY7R7Bm7Mz6kQpBx8TqlWbrtMDvkphHalwOKMzDz3eILlC/dnB7vOeqZK+Te6L/9P6vNDT4RDnpBkR3n8BYCDS8pGqNKvI/dwi6ZK1sQMQybpEDI+xzEdr6FRDmJGkit+V//yk65DD9rVbks9VOAc1rDKQv7cNULygpx0VZZ9TswoNtj/DoQE3vqxQGL4vtyrqyLQ1AewqRpeBaTewfkwnoNOB3SwjDJ5fzr0gepPGhsdPJm54dEVjE/98nCgjXVNQy4zHSj39UQ5L9G2tlhLSc5uw7dftacF4qROJdCXdhUcSkPqyioJwpAx9AANufywSj4ymGgmBJQF4C3gCwdkFtkISIwpqyO2uM/YrZKVQ1HZUEHg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
