travis:
  secure:
    BINSTAR_TOKEN: p/YFdwjtu0gFo1JP58cbrU0fZ00l1aMhLJ9uQlmXZljlrQF1HJoQ/4vSFSuBISA7wTRtJSuhtRB0x28c+ql5dBnlnw55Ah0jYZKcXD8tUWzTc3pRAvEE9B+kKFrwxpfU+zO+DUL55+MZV3okKF9z3TbY9GXzKBn0kxZanm36yNN3M01O4Ut+7zjF4dyhax2OmEzmWOsQ7O1UUJ2ZlWlx/4wouSli7r5xUrKEkClHPcTw0gsIBtpB5vvFDjWyg+M6KjXwH7MzXzjKs02c8gRagW0BR4tjrhc7BzcTupjebO74ImV1SdOErGszY9UgaAdikkEI4vbufXz6gnbESvhbXL+rB+tyi8AB6S3Egn78CnN5CdWq/5FGklVJLpSOqrw6sjdmmxoTC84kw3ISiFukATtjD+eBI2BRi8m5OK0fTPr6z9f5yAXfs7ZQM2T5gKzBBw5TIhUK+R9127fV34MXntqpI5TOxJGBvQfvjOcOdaQZ+PZla74lSH2lXtXI49AO0tw97oGFnjKq2NBR1H92eagZaVHFCnyNESOiUE9Zjqrid1TvHbpzbA8R+w8nUCXwgxDa8GzgslGjPt3EOgv4lQKl/ht1YCkkMzJ29NIyQM983GLncXJ2X1D1CBxjle90a6t9tEL8a7e/y09Bq1X6YIvSznmO1Byvbf5yYxSi3mw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
